=== johantre/XsltSprintReviewPC/bigenablers/style/sprint-review.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" attributeFormDefault="unqualified" elementFormDefault="qualified">
    <xs:element name="sprintreview">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="team" maxOccurs="1" minOccurs="1">
                    <xs:complexType>
                        <xs:sequence maxOccurs="1" minOccurs="1">
                            <xs:element name="productowner" maxOccurs="1" minOccurs="0"/>
                            <xs:element name="scrummaster" maxOccurs="1" minOccurs="0"/>
                            <xs:element name="member" maxOccurs="unbounded" minOccurs="1"/>
                        </xs:sequence>
                        <xs:attribute type="xs:string" name="name" use="required"/>
                    </xs:complexType>
                </xs:element>
                
                <xs:element name="intro" maxOccurs="1" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence maxOccurs="1" minOccurs="1">
                            <xs:element name="slides" maxOccurs="1" minOccurs="1">
                                <xs:complexType>
                                    <xs:sequence maxOccurs="1" minOccurs="1">
                                        <xs:element name="slide" type="storySlideType" maxOccurs="unbounded" minOccurs="1"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute type="xs:string" name="title" use="required"/>
                    </xs:complexType>
                </xs:element>
                
                <xs:element name="stories" maxOccurs="1" minOccurs="1">
                    <xs:complexType>
                        <xs:sequence maxOccurs="1" minOccurs="1">
                            <xs:element type="storyType" name="story" maxOccurs="unbounded" minOccurs="1" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute type="folderType" name="folder" use="required" />
        </xs:complexType>
    </xs:element>
    
    <xs:complexType name="storyType">
        <xs:sequence>
            <xs:element name="slides">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="slide" type="storySlideType" maxOccurs="unbounded" minOccurs="1" />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="title" type="xs:string" use="optional" />
        <xs:attribute name="state" type="stateType" use="optional" />
        <xs:attribute name="points" type="xs:int" use="optional" />
        <xs:attribute name="mksid" type="xs:double" use="optional" />    
    </xs:complexType>
    
    <xs:simpleType name="folderType">
        <xs:restriction base="xs:string">
            <xs:minLength value="1" />
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="storySlideType">
        <xs:sequence minOccurs="0" maxOccurs="unbounded">
            <xs:any processContents="lax" minOccurs="0" maxOccurs="unbounded" namespace="##any"/>
        </xs:sequence>
        <xs:attribute name="type">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="model-context" />
                    <xs:enumeration value="story-context" />
                    <xs:enumeration value="story-narrative" />
                    <xs:enumeration value="story-demo" />
                    <xs:enumeration value="story-timeline" />
                    <xs:enumeration value="story-code-q" />
                    <xs:enumeration value="whats-next" />
                    <xs:enumeration value="sprint-intro" />
                    <xs:enumeration value="sprint-goal" />
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>

    <xs:simpleType name="stateType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="story done"></xs:enumeration>
            <xs:enumeration value="story uncommitted"></xs:enumeration>
            <xs:enumeration value="story not-done"></xs:enumeration>
            <xs:enumeration value="bug"></xs:enumeration>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== johantre/XsltSprintReviewPC/itsbackoffice/140728/sprint-review.xml
<?xml version="1.0" encoding="Windows-1252" ?><?xml-stylesheet type="text/xsl" href="../../style/slides.xsl"?>
<sprintreview folder="140728" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../style/sprint-review.xsd">
    <team name="ITSbackoffice">
        <member type="productowner" capacity="0">Pieter Clavie </member>
        <member type="scrummaster" capacity="3">Denis Bollinne</member>
        <member type="hands-on" capacity="0">Gauthier Rossion </member>
        <member type="hands-on" capacity="0">Marnix De Groote </member>
        <member type="hands-on" capacity="0">Martijn Evens </member>
        <member type="hands-on" capacity="0">Thierry Habart </member>
        <member type="hands-on" capacity="8">Ignacio Errico </member>
        <member type="hands-on" capacity="4">Serge Van Meerbeeck</member>
        <member type="hands-on" capacity="8">Blaise Braye </member>
        <member type="tester" capacity="2.5">Annelies Ivens </member>
        <member type="tester" capacity="6">Parisa Pejham </member>
        <member type="tester" capacity="0">Kim Van Weyenbergh</member>
        <member type="assisted" capacity="0">Julia Dubois </member>
        <member type="assisted" capacity="0">Johan Tre</member>
        <member type="assisted" capacity="0">Christophe Lemoine</member>
    </team> 
  
    <metrics>
        <metric project="ServiceSupportManager" linesofcode="35730" stepfiles="0" unittests="261" complexity="15.066" />
        <metric project="PoiTracker" linesofcode="10978" stepfiles="0" unittests="151" complexity="13.6227" />
        <metric project="Transmodel.Netex" linesofcode="29605" stepfiles="24" unittests="462" complexity="12.3833" />
        <metric project="DetourManager" linesofcode="17625" stepfiles="2" unittests="382" complexity="8.89249" />
        <metric project="JobOrchestration" linesofcode="2962" stepfiles="0" unittests="81" complexity="7.20614" />
	</metrics>

   <stories>
		<story id="MOBITS-1189" relid="14524" points="3" state="story done" title="As an obstruction manager I want to select an impacted journey pattern via a treeview"><slides><slide type="story-narrative"></slide></slides></story>
		<story id="MOBITS-1608" relid="14524" points="2" state="story done" title="As a Planner I want to create a core Dataset from NeTEx"><slides><slide type="story-narrative"></slide></slides></story>
		<story id="MOBITS-1703" relid="14524" points="3" state="story done" title="As a Tco I want to access the obstruction module"><slides><slide type="story-narrative"></slide></slides></story>
		<story id="MOBITS-1881" relid="14524" points="2" state="story done" title="Polish tooltip journey pattern on the map in obstruction and detours"><slides><slide type="story-narrative"></slide></slides></story>
		<story id="MOBITS-1943" relid="14524" points="1" state="story done" title="Spike - As an installer I want a better installer"><slides><slide type="story-narrative"></slide></slides></story>
		<story id="MOBITS-1962" relid="14524" points="1" state="story done" title="In Queries replace Any() or Count &lt; 0 with ReturnOnEmptyList"><slides><slide type="story-narrative"></slide></slides></story>
		<story id="MOBITS-2029" relid="14524" points="3" state="story done" title="Testcases to update"><slides><slide type="story-narrative"></slide></slides></story>
		<story id="MOBITS-2084" relid="14524" points="1" state="story done" title="Obstruction manager view model has too many responsibilities"><slides><slide type="story-narrative"></slide></slides></story>
		<story id="MOBITS-2094" relid="14524" points="1" state="story done" title="Validate latest VDV452 export"><slides><slide type="story-narrative"></slide></slides></story>
		<story id="MOBITS-2095" relid="14524" points="1" state="story done" title="Reduce complexity of GeocodeSearchViewModel"><slides><slide type="story-narrative"></slide></slides></story>
		<story id="MOBITS-2097" relid="14524" points="1" state="story done" title="Split up Its.shared in seperate dlls"><slides><slide type="story-narrative"></slide></slides></story>
		<story id="MOBITS-2109" relid="14524" points="2" state="story done" title="As a Planner I want to create a UI for the datasetcreator"><slides><slide type="story-narrative"></slide></slides></story>
		<story id="MOBITS-1873" relid="14524" points="2" state="story not-done" percentage-done="90"  title="Polish highlighted journey pattern on the maps of obstruction and detours"><slides><slide type="story-narrative"></slide></slides></story>
		<story id="MOBITS-1889" relid="14524" points="2" state="story not-done" percentage-done="65"  title="Delete mappings after delete tmp stop - FF"><slides><slide type="story-narrative"></slide></slides></story>
		<story id="MOBITS-2108" relid="14524" points="3" state="story not-done" percentage-done="70"  title="As a Planner I want a core Dataset from NeTEx with a Header, schedule Info, Calendar, Block and Vehicle Journey"><slides><slide type="story-narrative"></slide></slides></story>
   
    </stories>

</sprintreview>

=== johantre/XsltSprintReviewPC/team-ba/140404/sprint-review.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="../../style/slides.xsl"?>

<sprintreview folder="140404" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../style/sprint-review.xsd">
    <team name="team-ba">
        <member type="scrummaster" capacity="0">Alexander </member>
        <member type="hands-on" capacity="4">Jan </member>
        <member type="hands-on" capacity="3.5">Saskia </member>
        <member type="hands-on" capacity="4">Michiel </member>
        <member type="hands-on" capacity="4">Jetro </member>
    </team>

    <stories> <!-- state can be: "story done" | "story not-done" | "story uncommitted" | "bug"  -->
        <story state="story done" points="1" title="KB: privacy routines (verwijderen persoonsgegevens)"><slides><slide type="story-narrative"></slide></slides></story>
        <story state="story not-done" percentage-done="30" points="1.25" title="Matrix 5 Verkoop: Nazorg "><slides><slide type="story-narrative"></slide></slides></story>
        <story state="story done" points="0.5" title="Update MOBIB kaartbeheer: update LIM/SNM (Timeboxed)"><slides><slide type="story-narrative"></slide></slides></story>
        <story state="story done" points="0.25" title="Review SS AVU-31 Rechthebbenden VVK"><slides><slide type="story-narrative"></slide></slides></story>
        <story state="story done" points="3" title="VVK: Verwerking review comments VVK verkoop (UCM/UCSS/LIM/SNM)"><slides><slide type="story-narrative"></slide></slides></story>
        <story state="story done" points="1.25" title="PO"><slides><slide type="story-narrative"></slide></slides></story>
        <story state="story not-done" percentage-done="70" points="1.25" title="Verwerking feedback kickoff 21/3"><slides><slide type="story-narrative"></slide></slides></story>
        <story state="story done" points="1" title="Update WBS"><slides><slide type="story-narrative"></slide></slides></story>
        <story state="story not-done" percentage-done="0" points="1" title="KB: alternatieve scenario's (RR onbeschikbaar; detectie dubbels van klanten; eID lezer onbeschikbaar; veranderd INSZ nummer...)"><slides><slide type="story-narrative"></slide></slides></story>
        <story state="story not-done" percentage-done="25" points="1.25" title="IKB: terugbetalingen te veel betaald"><slides><slide type="story-narrative"></slide></slides></story>
        <story state="story done" points="0.5" title="DBS: meeting rond impact DBS op KB, Verkoop, inkomstenbeheer (Timeboxed!)"><slides><slide type="story-narrative"></slide></slides></story>
        <story state="story done" points="3.75" title="DBS: core DBS analyse (LIM, UCM, SNM, UCSS)"><slides><slide type="story-narrative"></slide></slides></story>
   </stories>       

</sprintreview>

=== johantre/XsltSprintReviewPC/itsbackoffice/140331/sprint-review.xml
<?xml version="1.0"?><?xml-stylesheet type="text/xsl" href="../../style/slides.xsl"?>
<sprintreview folder="140331" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../style/sprint-review.xsd">
    <team name="ITSbackoffice">
        <member type="productowner" capacity="0">Pieter Clavie </member>
        <member type="scrummaster" capacity="4">Servaas Phlips </member>
        <member type="hands-on" capacity="5">Gauthier Rossion </member>
        <member type="hands-on" capacity="0">Marnix De Groote </member>
        <member type="hands-on" capacity="0">Martijn Evens </member>
        <member type="hands-on" capacity="8">Ignacio Errico </member>
        <member type="hands-on" capacity="7">Serge Van Meerbeeck</member>
        <member type="hands-on" capacity="8">Blaise Braye </member>
        <member type="tester" capacity="3.5">Annelies Ivens </member>
        <member type="tester" capacity="6">Parisa Pejham </member>
        <member type="assisted" capacity="0">Julia Dubois </member>
        <member type="assisted" capacity="0">Johan Tre</member>
        <member type="assisted" capacity="0">Christophe Lemoine </member>
    </team>     

    <stories>
		<story id="MOBITS-886" relid="13897" points="3" state="story done" title="As an obstruction manager I want to have a datepicker"><slides><slide type="story-narrative"></slide></slides></story>
		<story id="MOBITS-1366" relid="13897" points="3" state="story done" title="As a TCO I want advanced symbology in POITRACKER Tco"><slides><slide type="story-narrative"></slide></slides></story>
		<story id="MOBITS-1371" relid="13897" points="2" state="story done" title="Refactor timetable"><slides><slide type="story-narrative"></slide></slides></story>
		<story id="MOBITS-1473" relid="13897" points="3" state="story done" title="As an Obstruction manager I want a better overview printout for my detour"><slides><slide type="story-narrative"></slide></slides></story>
		<story id="MOBITS-1474" relid="13897" points="3" state="story done" title="SPIKE: As an obstruction manager I want to be able to add text annotation to the print out maps"><slides><slide type="story-narrative"></slide></slides></story>
		<story id="MOBITS-1480" relid="13897" points="5" state="story done" title="As an obstruction manager I want to save a draft obstruction in an invalid state"><slides><slide type="story-narrative"></slide></slides></story>
		<story id="MOBITS-1539" relid="13897" points="1" state="story done" title=" As an obstruction manager I want to warned when my unsaved changes will be lost SIMPLE VERSION"><slides><slide type="story-narrative"></slide></slides></story>
		<story id="MOBITS-1545" relid="13897" points="3" state="story done" title="switch to new teamcity server part2"><slides><slide type="story-narrative"></slide></slides></story>
		<story id="MOBITS-1549" relid="13897" points="2" state="story done" title="As a TCO I want my TCO mode"><slides><slide type="story-narrative"></slide></slides></story>
		<story id="MOBITS-1553" relid="13897" points="3" state="story done" title="Stopzone Feature Files"><slides><slide type="story-narrative"></slide></slides></story>
		<story id="MOBITS-1554" relid="13897" points="2" state="story done" title="Merge and Branch from 2.6 to 2.7"><slides><slide type="story-narrative"></slide></slides></story>
    	<story id="MOBITS-1547" points="3" state="story done" title="Create main entry point and ITS Client"><slides><slide type="story-narrative"></slide></slides></story>
   
    </stories>

</sprintreview>

=== johantre/XsltSprintReviewPC/ccbo/140331/sprint-review.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="../style/slides.xsl"?>

<sprintreview folder="140331" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../style/sprint-review.xsd">
    <team name="Team CCBO">
        <member type="scrummaster" capacity="5">Fares Stita </member>
        <member type="hands-on" capacity="10">Gerrit Hernou </member>
        <member type="hands-on" capacity="10">Koenraad De Bisschop </member>
        <member type="tester" capacity="10">Johan Santamaria </member>
    </team>

    <stories> <!-- state can be: "story done" | "story not-done" | "story uncommitted" | "bug"  -->
        <story title="" state="story done" points="0"><slides><slide type="story-narrative"></slide></slides></story>
        <story title="" state="story done" points="0"><slides><slide type="story-narrative"></slide></slides></story>
        <story title="" state="story done" points="0"><slides><slide type="story-narrative"></slide></slides></story>
        <story title="" state="story done" points="0"><slides><slide type="story-narrative"></slide></slides></story>
        <story title="" state="story done" points="0"><slides><slide type="story-narrative"></slide></slides></story>
        <story title="" state="story done" points="0"><slides><slide type="story-narrative"></slide></slides></story>
        <story title="" state="story done" points="0"><slides><slide type="story-narrative"></slide></slides></story>
        <story title="" state="story done" points="0"><slides><slide type="story-narrative"></slide></slides></story>
        <story title="" state="story done" points="0"><slides><slide type="story-narrative"></slide></slides></story>
        <story title="" state="story done" points="0"><slides><slide type="story-narrative"></slide></slides></story>
        <story title="" state="story done" points="0"><slides><slide type="story-narrative"></slide></slides></story>
        <story title="" state="story done" points="0"><slides><slide type="story-narrative"></slide></slides></story>
        <story title="" state="story done" points="0"><slides><slide type="story-narrative"></slide></slides></story>
        <story title="" state="story done" points="0"><slides><slide type="story-narrative"></slide></slides></story>
        <story title="" state="story done" points="0"><slides><slide type="story-narrative"></slide></slides></story>
        <story title="" state="story done" points="0"><slides><slide type="story-narrative"></slide></slides></story>
        <story title="" state="story done" points="0"><slides><slide type="story-narrative"></slide></slides></story>
        <story title="" state="story done" points="0"><slides><slide type="story-narrative"></slide></slides></story>
        <story title="" state="story done" points="0"><slides><slide type="story-narrative"></slide></slides></story>
        <story title="" state="story done" points="0"><slides><slide type="story-narrative"></slide></slides></story>
        <story title="" state="story done" points="0"><slides><slide type="story-narrative"></slide></slides></story>
        <story title="" state="story done" points="0"><slides><slide type="story-narrative"></slide></slides></story>
        <story title="" state="story done" points="0"><slides><slide type="story-narrative"></slide></slides></story>
        <story title="" state="story done" points="0"><slides><slide type="story-narrative"></slide></slides></story>
   </stories>        

</sprintreview>

=== johantre/XsltSprintReviewPC/itsbackoffice/140602/sprint-review.xml
<?xml version="1.0"?><?xml-stylesheet type="text/xsl" href="../../style/slides.xsl"?>
<sprintreview folder="140602" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../style/sprint-review.xsd">
    <team name="ITSbackoffice">
        <member type="productowner" capacity="0">Pieter Clavie </member>
        <member type="assisted" capacity="0">Julia Dubois </member>
        <member type="assisted" capacity="0">Christophe Lemoine </member>
        <member type="hands-on" capacity="0">Martijn Evens </member>
        <member type="scrummaster" capacity="3.5">Servaas Phlips </member>
        <member type="hands-on" capacity="0">Ignacio Errico </member>
        <member type="hands-on" capacity="7">Blaise Braye </member>
        <member type="hands-on" capacity="7">Serge Van Meerbeeck</member>
        <member type="hands-on" capacity="4">Gauthier Rossion </member>
        <member type="tester" capacity="5">Annelies Ivens </member>
        <member type="tester" capacity="4">Parisa Pejham </member>
        <member type="hands-on" capacity="3.5">Marnix De Groote </member>
    </team> 

    <stories>
		<story id="MOBITS-1159"  points="5" state="story done" title="Detour Editor ViewModel - Make the same as obstruction editor"><slides><slide type="story-narrative"></slide></slides></story>
		<story id="MOBITS-1188" relid="13907" points="2" state="story done" title="As an obstruction manager I want to select valid impacted journey pattern for obstructions and detours"><slides><slide type="story-narrative"></slide></slides></story>
		<story id="MOBITS-1195" relid="13907" points="2" state="story done" title="As an obstruction manager I want to define the fare mapping"><slides><slide type="story-narrative"></slide></slides></story>
		<story id="MOBITS-1196" relid="13907" points="3" state="story done" title="As an obstruction manager I want to define the timing mapping"><slides><slide type="story-narrative"></slide></slides></story>
		<story id="MOBITS-1367" relid="13907" points="1" state="story done" title="As a TCO I want a better lock poi functunality in POITRACKER Tco"><slides><slide type="story-narrative"></slide></slides></story>
		<story id="MOBITS-1543"  points="2" state="story done" title="PVS Control Server - Send commands and receive response"><slides><slide type="story-narrative"></slide></slides></story>
		<story id="MOBITS-1826"  points="2" state="story done" title="Have consistent usage of spatial representation"><slides><slide type="story-narrative"></slide></slides></story>
		<story id="MOBITS-1853"  points="2" state="story done" title="Add Pivot Navigator to Detour Editor"><slides><slide type="story-narrative"></slide></slides></story>
		<story id="MOBITS-1887"  points="2" state="story done" title="Implement step file for feature file timing mapping"><slides><slide type="story-narrative"></slide></slides></story>
        <story id="MOBITS-1841" relid="13907" points="5" state="story not-done" percentage-done="85"  title="As an obstruction manager I want to create a new version frame after a publish"><slides><slide type="story-narrative"></slide></slides></story>
    </stories>

</sprintreview>

=== johantre/XsltSprintReviewPC/besharp/141006/sprint-review.xml
<?xml version="1.0"?><?xml-stylesheet type="text/xsl" href="../../style/slides.xsl"?>
<sprintreview folder="141006" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../style/sprint-review.xsd">
    <team name="BeSharp">
        <member type="productowner" capacity="0">Pieter Clavie </member>
        <member type="scrummaster" capacity="4">Denis Bollinne</member>
        <member type="hands-on" capacity="8">Marnix De Groote </member>
        <member type="hands-on" capacity="0">Martijn Evens </member>
        <member type="hands-on" capacity="8">Ignacio Errico </member>
        <member type="hands-on" capacity="8">Blaise Braye </member>
        <member type="tester" capacity="6">Parisa Pejham </member>
    </team>

  <intro>
    <slides>
      <slide title="current sprint" type="sprint-goal">
        <List xmlns="http://schemas.microsoft.com/sharepoint/">
          <b>Being able to estimate the Hastus import changes.</b>
        </List>
      </slide>  
    </slides>
  </intro>

  <metrics>
    <metric project="Transmodel.Netex" linesofcode="37992" stepfiles="75" unittests="517" complexity="9.847571189" />
    <metric project="JobOrchestration" linesofcode="3520" stepfiles="0" unittests="108" complexity="7.348148148" />
  </metrics>
  
    <stories>
		<story id="MOBITS-1593" relid="14524" points="2" state="story done" title="Enable stylecop for PoiTracker and fix"><slides><slide type="story-narrative"></slide></slides></story>
		<story id="MOBITS-1799" relid="14524" points="3" state="story done" title="As a planner I want the activation points inside the dataset"><slides><slide type="story-narrative"></slide></slides></story>
		<story id="MOBITS-2408" relid="14524" points="3" state="story done" title="As a planner I want a dataset on the board computer"><slides><slide type="story-narrative"></slide></slides></story>
		<story id="MOBITS-2466" relid="14524" points="1" state="story done" title="Review Manuals - Team Denis"><slides><slide type="story-narrative"></slide></slides></story>
		<story id="MOBITS-2341" relid="14524" points="5" state="story not-done" percentage-done="70"  title="As a client for the AVL service I want Train Messsages with context"><slides><slide type="story-narrative"></slide></slides></story>
		<story id="MOBITS-2362" relid="14524" points="3" state="story not-done" percentage-done="0"  title=" As a client for the AVL service I want Only Bus Messsages with context (technical implementation)"><slides><slide type="story-narrative"></slide></slides></story>
		<story id="MOBITS-2465" relid="14524" points="3" state="story not-done" percentage-done="0"  title="Writing usability cases part 2 - Team Denis"><slides><slide type="story-narrative"></slide></slides></story>
		<story id="MOBITS-2467" relid="14524" points="5" state="story not-done" percentage-done="50"  title="Import vehicle service &amp; block associations"><slides><slide type="story-narrative"></slide></slides></story>
		<story id="MOBITS-2468" relid="14524" points="3" state="story not-done" percentage-done="0"  title="Import block &amp; vehicle journey association"><slides><slide type="story-narrative"></slide></slides></story>
    	<story id="MOBITS-2514" relid="14524" points="0" state="story uncommitted" title="[DB Remodeling] Update DB and EDMX"><slides><slide type="story-narrative"></slide></slides></story>
   
    </stories>

</sprintreview>
