=== johantre/XsltSprintReviewPC/bigenablers/style/sprint-review.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" attributeFormDefault="unqualified" elementFormDefault="qualified">
    <xs:element name="sprintreview">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="team" maxOccurs="1" minOccurs="1">
                    <xs:complexType>
                        <xs:sequence maxOccurs="1" minOccurs="1">
                            <xs:element name="productowner" maxOccurs="1" minOccurs="0"/>
                            <xs:element name="scrummaster" maxOccurs="1" minOccurs="0"/>
                            <xs:element name="member" maxOccurs="unbounded" minOccurs="1"/>
                        </xs:sequence>
                        <xs:attribute type="xs:string" name="name" use="required"/>
                    </xs:complexType>
                </xs:element>
                
                <xs:element name="intro" maxOccurs="1" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence maxOccurs="1" minOccurs="1">
                            <xs:element name="slides" maxOccurs="1" minOccurs="1">
                                <xs:complexType>
                                    <xs:sequence maxOccurs="1" minOccurs="1">
                                        <xs:element name="slide" type="storySlideType" maxOccurs="unbounded" minOccurs="1"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute type="xs:string" name="title" use="required"/>
                    </xs:complexType>
                </xs:element>
                
                <xs:element name="stories" maxOccurs="1" minOccurs="1">
                    <xs:complexType>
                        <xs:sequence maxOccurs="1" minOccurs="1">
                            <xs:element type="storyType" name="story" maxOccurs="unbounded" minOccurs="1" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute type="folderType" name="folder" use="required" />
        </xs:complexType>
    </xs:element>
    
    <xs:complexType name="storyType">
        <xs:sequence>
            <xs:element name="slides">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="slide" type="storySlideType" maxOccurs="unbounded" minOccurs="1" />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="title" type="xs:string" use="optional" />
        <xs:attribute name="state" type="stateType" use="optional" />
        <xs:attribute name="points" type="xs:int" use="optional" />
        <xs:attribute name="mksid" type="xs:double" use="optional" />    
    </xs:complexType>
    
    <xs:simpleType name="folderType">
        <xs:restriction base="xs:string">
            <xs:minLength value="1" />
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="storySlideType">
        <xs:sequence minOccurs="0" maxOccurs="unbounded">
            <xs:any processContents="lax" minOccurs="0" maxOccurs="unbounded" namespace="##any"/>
        </xs:sequence>
        <xs:attribute name="type">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="model-context" />
                    <xs:enumeration value="story-context" />
                    <xs:enumeration value="story-narrative" />
                    <xs:enumeration value="story-demo" />
                    <xs:enumeration value="story-timeline" />
                    <xs:enumeration value="story-code-q" />
                    <xs:enumeration value="whats-next" />
                    <xs:enumeration value="sprint-intro" />
                    <xs:enumeration value="sprint-goal" />
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>

    <xs:simpleType name="stateType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="story done"></xs:enumeration>
            <xs:enumeration value="story uncommitted"></xs:enumeration>
            <xs:enumeration value="story not-done"></xs:enumeration>
            <xs:enumeration value="bug"></xs:enumeration>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== johantre/XsltSprintReviewPC/techTeam/140814/sprint-review.xml
<?xml version="1.0"?><?xml-stylesheet type="text/xsl" href="../../style/slides.xsl"?>
<sprintreview folder="140814" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../style/sprint-review.xsd">
        <team name="TechTeam">
        <member type="scrummaster" capacity="0">Michael De Maessschalck </member>
        <member type="hands-on" capacity="8">Bjorn Bailleul </member>
        <member type="hands-on" capacity="9">Philip Van Hoof</member>
        <member type="hands-on" capacity="9">Steven Robijns </member>
        <member type="tester" capacity="9">Dorine Vos </member>
        <member type="tester" capacity="3">Niels Beckers </member>
        <member type="productowner" capacity="0">Rudi Windey </member>
        <member type="productowner" capacity="0">Wouter Crets </member>
</team>       

<intro>
    	<slides>
		  <slide title="UNPLANNED WORK" type="story-batman">
			<List xmlns="http://schemas.microsoft.com/sharepoint/">
			  <li>[RM] Integratie Release Mgt Rapport (change request)</li>
			  <li>[CM] Importeer Locaties (change request)</li>
			  <li>Aanmaak 3.2 branch</li>
			  <li>FO QA support</li>
			  <br/>
			</List>
		  </slide>
	      <slide title="Overzicht" type="story-context">
	        <List xmlns="http://schemas.microsoft.com/sharepoint/">
	          <strong>AVU R2</strong>
	          <li>Installatie en sanity checks</li>
			  <br/>
			  <strong>ABO R2</strong>
			  <li>Installatie en sanity checks</li>
	          <li>Voorbereiding performance testing Event Mgt</li>
			  <br/>  
			  <strong>ABO R3</strong>          
	          <li>Account Management: LIM en eerste UCs</li>
	          <li>Product Management: artikelbeheer</li>
			  <br/>
	        </List>
	      </slide>		
		</slides>
</intro>

    <stories>
		<story id="DL-12672" relid="03" points="4.5" state="story done" title="[RM] Oplevering 18/8"><slides><slide type="story-narrative"></slide></slides></story>
		<story id="DL-12673" relid="03" points="0.25" state="story done" title="[EM] Oplevering 18/8"><slides><slide type="story-narrative"></slide></slides></story>
		                            
		<story id="DL-12676" relid="04" points="0.125" state="story done" title="[TM] Scherm: zoeken Artikel"><slides><slide type="story-narrative"></slide></slides></story>
		<story id="DL-12680" relid="04" points="0.125" state="story done" title="[TM]Scherm: raadplegen Artikel"><slides><slide type="story-narrative"></slide></slides></story>
		<story id="DL-12762" relid="04" points="0.25" state="story done" title="[TM] Scherm: Aanmaken Artikel"><slides><slide type="story-narrative"></slide></slides></story>   			
		                            
		<story id="DL-12695" relid="04" points="0" state="bug" title="[BranchAF]Resultatenlijst zoeken familie niet correct gesorteerd"><slides><slide type="story-narrative"></slide></slides></story>
		<story id="DL-12755" relid="04" points="0" state="bug" title="[BranchAF]Zoeken artikels: reset werkt niet voor checkboxen"><slides><slide type="story-narrative"></slide></slides></story>
		<story id="DL-12454" relid="01" points="0" state="bug" percentage-done="0"  title="EXT - Release Management: RM houdt geen rekening met wijzigingen aan releasegroep indien publicatie onmiddellijk erna gebeurt"><slides><slide type="story-narrative"></slide></slides></story>
		<story id="DL-12729" relid="04" points="0" state="bug" percentage-done="0"  title="[FW]Filter toont altijd 0 resultaten bij selecteren select item"><slides><slide type="story-narrative"></slide></slides></story>		
		<story id="DL-12714" relid="01" points="0" state="bug" percentage-done="0"  title="Creatie delta: veplichte java package aanwezig die er geen mag zijn"><slides><slide type="story-narrative"></slide></slides></story>
		<story id="DL-12732" relid="04" points="0" state="bug" title="[FW] Na verwijdering release blijft Verwijder knop actief en algemene status incorrect"><slides><slide type="story-narrative"></slide></slides></story>
    	<story id="DL-12790" relid="04" points="0" state="bug" title="[BranchAF] Detail artikel: BTW veld toont naam ipv btw"><slides><slide type="story-narrative"></slide></slides></story>		
    	<story id="DL-12742" relid="04" points="0" state="bug" title="[BranchAF] Wijzigen Attributenlijst: verplichte attributen mogen niet verwijderd worden"><slides><slide type="story-narrative"></slide></slides></story>
    	<story id="DL-12789" relid="04" points="0" state="bug" title="[BranchAF] Aanmaken artikel: alleen actieve families mogen beschikbaar zijn"><slides><slide type="story-narrative"></slide></slides></story>		
		                            
		<story id="DL-12677" relid="04" points="4" state="story not-done" percentage-done="85"  title="[FW] Framework upgrade"><slides><slide type="story-narrative"></slide></slides></story>
		                            
    	<story id="DL-12773" relid="06" points="3" state="story done" title="[AM] LIM Account Management"><slides><slide type="story-narrative"></slide></slides></story>		
		<story id="DL-12827" relid="04" points="2" state="story uncommitted" percentage-done="75"  title="[AM] Creeer account"><slides><slide type="story-narrative"></slide></slides></story>
		<story id="DL-12828" relid="04" points="2" state="story uncommitted" percentage-done="75"  title="[AM] Creeer contract"><slides><slide type="story-narrative"></slide></slides></story>
		<story id="DL-12829" relid="04" points="2" state="story uncommitted" percentage-done="75"  title="[AM] Geef account"><slides><slide type="story-narrative"></slide></slides></story>
		                            
    	<story id="DL-12772" relid="03" points="2" state="story done" title="[RM], [TM] en [LOG] Bug fixing"><slides><slide type="story-narrative"></slide></slides></story>
    	                            
    	<story id="DL-12826" relid="03" points="0" state="story done" title="[OPS] Uitbreiden Nservicebushost tool voor Event Mgt"><slides><slide type="story-narrative"></slide></slides></story>
    	                            
    	<story id="DL-12838" relid="03" points="0" state="story uncommitted" percentage-done="75"  title="[RM] Integratie Release Mgt Rapport"><slides><slide type="story-narrative"></slide></slides></story>
		<story id="DL-12824" relid="03" points="0" state="story uncommitted" percentage-done="75"  title="[CM] Importeer Locaties"><slides><slide type="story-narrative"></slide></slides></story>
    	
  
    </stories>

</sprintreview>

=== johantre/XsltSprintReviewPC/canguru/140320/sprint-review.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="../../style/slides.xsl"?>

<sprintreview folder="140320" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../style/sprint-review.xsd">
  <team name="CanGuru">
    <member type="scrummaster" capacity="0.0" avatar="../avatars/Bjorn.jpg">Bjorn Geuns</member>
    <member type="hands-on" capacity="8.0" avatar="../avatars/laurens.jpg">Laurens Robben </member>
    <member type="hands-on" capacity="5.0" avatar="../avatars/Joeri.jpg">Joeri Marcoen</member>
    <member type="hands-on" capacity="8.0" avatar="../avatars/Maarten.jpg">Maarten Claes</member>
    <member type="tester" capacity="8.0" avatar="../avatars/Carmen.jpg">Carmen Filippo</member>
    <member type="tester" capacity="7.5" avatar="../avatars/Carol.jpg">Carol Guns</member>
    <member type="tester" capacity="8.0" avatar="../avatars/Kim.jpg">Kim Van Weyenbergh</member>
    <member type="productowner" capacity="0.0" avatar="../avatars/Saskia.jpg">Saskia Van Oldenborgh</member>
    <member type="productowner" capacity="0.0" avatar="../avatars/Jan.jpg">Jan Van der Borght</member>
    <member type="productowner" capacity="0.0" avatar="../avatars/Jetro.jpg">Jetro Wils</member>
  </team>


  <stories>

    <story title="DL-11464 [V00] finalize MOBIB integratie" state="story done" points="0.5" id="DL-11464">
      <slides>
        <slide type="story-narrative"></slide>
      </slides>
    </story>
    <story title="DL-11465 [V00] Test MOBIB integratie" state="story done" points="0.5" id="DL-11465">
      <slides>
        <slide type="story-narrative"></slide>
      </slides>
    </story>
    <story title="DL-11472 [V00] hertest bugfix DL-11163 [V00] externe personalisatie leverancier feedback wordt verkeerd verwerkt" state="story not-done" points="1" id="DL-11472" percentage-done="0">
      <slides>
        <slide type="story-narrative"></slide>
      </slides>
    </story>

    <story title="DL-11224 [VVK] Implementeer Start externe personalisatiebatch" state="story done" points="3.5" id="DL-11224">
      <slides>
        <slide type="story-narrative"></slide>
      </slides>
    </story>
    <story title="DL-11461 [VVK] prelim test New lib from IntoIT" state="story done" points="1" id="DL-11461">
      <slides>
        <slide type="story-narrative"></slide>
      </slides>
    </story>
    <story title="DL-11462 [VVK] performance counters op de componenten" state="story done" points="1" id="DL-11462">
      <slides>
        <slide type="story-narrative"></slide>
      </slides>
    </story>
    <story title="DL-11463 [VVK] extended logging op de componenten + logservice (Q&quot;D)" state="story done" points="3" id="DL-11463">
      <slides>
        <slide type="story-narrative"></slide>
      </slides>
    </story>
    <story title="DL-11470 [VVK] inventaris ontbrekende unit testen" state="story done" points="0.5" id="DL-11470">
      <slides>
        <slide type="story-narrative"></slide>
      </slides>
    </story>
    <story title="DL-11471 [VVK] DEMO DL voorbereiden" state="story done" points="5.5" id="DL-11471">
      <slides>
        <slide type="story-narrative"></slide>
      </slides>
    </story>
    <story title="DL-11466 [VVK] TIMEBOX test VVK gebaseerd op FF" state="story not-done" points="3" id="DL-11466" percentage-done="30">
      <slides>
        <slide type="story-narrative"></slide>
      </slides>
    </story>
    <story title="DL-11467 [VVK] concurreny tests (manueel)" state="story not-done" points="3" id="DL-11467" percentage-done="0">
      <slides>
        <slide type="story-narrative"></slide>
      </slides>
    </story>
    <story title="DL-11473 [ABO] TIMEBOX review UC's" state="story done" points="3" id="DL-11473">
      <slides>
        <slide type="story-narrative"></slide>
      </slides>
    </story>
    <story title="DL-11469 [ABO][TARIFF] format voor QA + BA coop" state="story done" points="0.5" id="DL-11469">
      <slides>
        <slide type="story-narrative"></slide>
      </slides>
    </story>
    <story title="DL-11468 [ABO][TARIFF] TIMEBOX inwerken, Domein kennis vergaren" state="story not-done" points="3" id="DL-11468" percentage-done="0">
      <slides>
        <slide type="story-narrative"></slide>
      </slides>
    </story>
    <story title="DL-11009 [KB] Sanity check" state="story done" points="2" id="DL-11009">
      <slides>
        <slide type="story-narrative"></slide>
      </slides>
    </story>
    <story title="DL-11015 [KB] Check manually DL-9314 Start klantenbeheer" state="story done" points="0.5" id="DL-11015">
      <slides>
        <slide type="story-narrative"></slide>
      </slides>
    </story>
    <story title="DL-11016 [KB] Check manually DL-9317 Toon details persoon" state="story done" points="0.5" id="DL-11016">
      <slides>
        <slide type="story-narrative"></slide>
      </slides>
    </story>
    <story title="DL-11017 [KB] Check manually DL-9328 Toon details contactpersoon" state="story done" points="0.5" id="DL-11017">
      <slides>
        <slide type="story-narrative"></slide>
      </slides>
    </story>
    <story title="DL-11018 [KB] Check manually DL-9326 Toon adres details" state="story done" points="0.5" id="DL-11018">
      <slides>
        <slide type="story-narrative"></slide>
      </slides>
    </story>
    <story title="DL-11019 [KB] Check manually DL-9322 Voeg pasfoto toe via upload" state="story done" points="0.5" id="DL-11019">
      <slides>
        <slide type="story-narrative"></slide>
      </slides>
    </story>
    <story title="DL-11020 [KB] Check manually DL-9323 Zoek klant" state="story done" points="0.5" id="DL-11020">
      <slides>
        <slide type="story-narrative"></slide>
      </slides>
    </story>
    <story title="DL-11021 [KB] Check manually DL-9324 Filter klanten" state="story done" points="0.5" id="DL-11021">
      <slides>
        <slide type="story-narrative"></slide>
      </slides>
    </story>
    <story title="DL-11022 [KB] Check manually DL-9325 Sorteer klanten" state="story done" points="0.5" id="DL-11022">
      <slides>
        <slide type="story-narrative"></slide>
      </slides>
    </story>
    <story title="DL-11023 [KB] Check manually DL-9327 Filter adressen" state="story not-done" points="0.5" id="DL-11023" percentage-done="25">
      <slides>
        <slide type="story-narrative"></slide>
      </slides>
    </story>
    <story title="DL-11024 [KB] Check manually DL-9331 Zoek medewerker" state="story not-done" points="0.5" id="DL-11024" percentage-done="25">
      <slides>
        <slide type="story-narrative"></slide>
      </slides>
    </story>
    <story title="DL-11025 [KB] Check manually DL-9332 Filter medewerkers" state="story done" points="0.5" id="DL-11025" >
      <slides>
        <slide type="story-narrative"></slide>
      </slides>
    </story>
    <story title="DL-11026 [KB] Check manually DL-9333 Sorteer medewerkers" state="story done" points="0.5" id="DL-11026">
      <slides>
        <slide type="story-narrative"></slide>
      </slides>
    </story>
    <story title="RTBDEV-30 EXT - Opstart scherm(en) 65+ traag binnen mobiguider" state="story not-done" points="0" id="RTBDEV-30" percentage-done="50">
      <slides>
        <slide type="story-narrative"></slide>
      </slides>
    </story>
  </stories>

</sprintreview>

=== johantre/XsltSprintReviewPC/itsbackoffice/140317/sprint-review.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="../style/slides.xsl"?>

<sprintreview folder="140317" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../style/sprint-review.xsd">
    <team name="ITSbackoffice">
        <member type="productowner" capacity="0">Pieter Clavie </member>
        <member type="scrummaster" capacity="4">Servaas Phlips </member>
        <member type="hands-on" capacity="3">Gauthier Rossion </member>
        <member type="hands-on" capacity="5">Marnix De Groote </member>
        <member type="hands-on" capacity="0">Martijn Evens </member>
        <member type="hands-on" capacity="8">Ignacio Errico </member>
        <member type="hands-on" capacity="8">Serge Van Meerbeeck </member>
        <member type="hands-on" capacity="8">Blaise Braye </member>
        <member type="tester" capacity="0">Christophe Lemoine </member>        
        <member type="tester" capacity="7.5">Annelies Ivens </member>        
        <member type="tester" capacity="4">Parisa Pejham </member>
        <member type="assisted" capacity="0">Julia Dubois </member>
        <member type="assisted" capacity="0">Johan Tré </member>
    </team>

    <stories>
        <story id="MOBITS-1435" points="1" title="RELEASE - Create Branch" state="story done"><slides><slide type="story-narrative"></slide></slides></story>
        <story id="MOBITS-1437" points="2" title="RELEASE - Create teamcity config for its shared and switch to branch" state="story done"><slides><slide type="story-narrative"></slide></slides></story>
        <story id="MOBITS-1440" points="1" title="RELEASE -  V#" state="story done"><slides><slide type="story-narrative"></slide></slides></story>
        <story id="MOBITS-1438" points="1" title="RELEASE - Fix Installers" state="story done"><slides><slide type="story-narrative"></slide></slides></story>
        <story id="MOBITS-1436" points="2" title="RELEASE - Remove/Add User Stories" state="story done"><slides><slide type="story-narrative"></slide></slides></story>
        <story id="MOBITS-1439" points="1" title="RELEASE - QA Prepare DB Scripts" state="story done"><slides><slide type="story-narrative"></slide></slides></story>
        <story id="MOBITS-1441" points="1" title="RELEASE - QA End to end (+security)" state="story done"><slides><slide type="story-narrative"></slide></slides></story>
        <story id="MOBITS-1442" points="1" title="RELEASE - QA Stopzone" state="story done"><slides><slide type="story-narrative"></slide></slides></story>
        <story id="MOBITS-1443" points="1" title="RELEASE - QA Poi and SSM" state="story done"><slides><slide type="story-narrative"></slide></slides></story>
        <story id="MOBITS-1444" points="1" title="RELEASE - QA Localisation" state="story done"><slides><slide type="story-narrative"></slide></slides></story>
        <story id="MOBITS-1445" points="1" title="RELEASE - QA Job orchestration" state="story done"><slides><slide type="story-narrative"></slide></slides></story>
        <story id="MOBITS-1446" points="2" title="RELEASE - QA Obstruction and Detours" state="story done"><slides><slide type="story-narrative"></slide></slides></story>
        <story id="MOBITS-1423" points="3" title="Implement end to end feature file test for all entities of hastus import, only happy path scenarios" state="story done"><slides><slide type="story-narrative"></slide></slides></story>
        <story id="MOBITS-1430" points="5" title="Update Framework" state="story done"><slides><slide type="story-narrative"></slide></slides></story>
        <story id="MOBITS-1433" points="2" title="Investigate installer diagnostics tool" state="story done"><slides><slide type="story-narrative"></slide></slides></story>
        <story id="MOBITS-1426" points="1" title="To Refactor or not to refactor mapcontrol POI Tracker TCO" state="story done"><slides><slide type="story-narrative"></slide></slides></story>
        <story id="MOBITS-1406" points="3" title="As a TCO I want a better grid with advanced features in incoming messages" state="story done"><slides><slide type="story-narrative"></slide></slides></story>

    </stories>

</sprintreview>

=== johantre/XsltSprintReviewPC/techTeam/140228/sprint-review.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="../style/slides.xsl"?>

<sprintreview folder="140228" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../style/sprint-review.xsd">
    <team name="TechTeam">
        <member type="scrummaster" capacity="0">Michael D. </member>
        <member type="hands-on" capacity="4">Michael B. </member>
        <member type="hands-on" capacity="4">Philip </member>
        <member type="hands-on" capacity="4">Steven W. </member>
        <member type="hands-on" capacity="4">Steven R. </member>
        <member type="tester" capacity="4">Niels </member>
        <member type="tester" capacity="4">Dorien </member>
    </team>

    <stories> <!-- state can be: "story done" | "story not-done" | "story uncommitted" | "bug"  -->
        <story title="" state="story done" points="0"><slides><slide type="story-narrative"></slide></slides></story>
        <story title="" state="story done" points="0"><slides><slide type="story-narrative"></slide></slides></story>
        <story title="" state="story done" points="0"><slides><slide type="story-narrative"></slide></slides></story>
        <story title="" state="story done" points="0"><slides><slide type="story-narrative"></slide></slides></story>
        <story title="" state="story done" points="0"><slides><slide type="story-narrative"></slide></slides></story>
        <story title="" state="story done" points="0"><slides><slide type="story-narrative"></slide></slides></story>
        <story title="" state="story done" points="0"><slides><slide type="story-narrative"></slide></slides></story>
        <story title="" state="story done" points="0"><slides><slide type="story-narrative"></slide></slides></story>
        <story title="" state="story done" points="0"><slides><slide type="story-narrative"></slide></slides></story>
        <story title="" state="story done" points="0"><slides><slide type="story-narrative"></slide></slides></story>
        <story title="" state="story done" points="0"><slides><slide type="story-narrative"></slide></slides></story>
        <story title="" state="story done" points="0"><slides><slide type="story-narrative"></slide></slides></story>
        <story title="" state="story done" points="0"><slides><slide type="story-narrative"></slide></slides></story>
        <story title="" state="story done" points="0"><slides><slide type="story-narrative"></slide></slides></story>
        <story title="" state="story done" points="0"><slides><slide type="story-narrative"></slide></slides></story>
        <story title="" state="story done" points="0"><slides><slide type="story-narrative"></slide></slides></story>
        <story title="" state="story done" points="0"><slides><slide type="story-narrative"></slide></slides></story>
        <story title="" state="story done" points="0"><slides><slide type="story-narrative"></slide></slides></story>
        <story title="" state="story done" points="0"><slides><slide type="story-narrative"></slide></slides></story>
        <story title="" state="story done" points="0"><slides><slide type="story-narrative"></slide></slides></story>
        <story title="" state="story done" points="0"><slides><slide type="story-narrative"></slide></slides></story>
        <story title="" state="story done" points="0"><slides><slide type="story-narrative"></slide></slides></story>
        <story title="" state="story done" points="0"><slides><slide type="story-narrative"></slide></slides></story>
        <story title="" state="story done" points="0"><slides><slide type="story-narrative"></slide></slides></story>
   </stories>        

</sprintreview>
