=== johantre/XsltSprintReviewPC/bigenablers/style/sprint-review.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" attributeFormDefault="unqualified" elementFormDefault="qualified">
    <xs:element name="sprintreview">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="team" maxOccurs="1" minOccurs="1">
                    <xs:complexType>
                        <xs:sequence maxOccurs="1" minOccurs="1">
                            <xs:element name="productowner" maxOccurs="1" minOccurs="0"/>
                            <xs:element name="scrummaster" maxOccurs="1" minOccurs="0"/>
                            <xs:element name="member" maxOccurs="unbounded" minOccurs="1"/>
                        </xs:sequence>
                        <xs:attribute type="xs:string" name="name" use="required"/>
                    </xs:complexType>
                </xs:element>
                
                <xs:element name="intro" maxOccurs="1" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence maxOccurs="1" minOccurs="1">
                            <xs:element name="slides" maxOccurs="1" minOccurs="1">
                                <xs:complexType>
                                    <xs:sequence maxOccurs="1" minOccurs="1">
                                        <xs:element name="slide" type="storySlideType" maxOccurs="unbounded" minOccurs="1"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute type="xs:string" name="title" use="required"/>
                    </xs:complexType>
                </xs:element>
                
                <xs:element name="stories" maxOccurs="1" minOccurs="1">
                    <xs:complexType>
                        <xs:sequence maxOccurs="1" minOccurs="1">
                            <xs:element type="storyType" name="story" maxOccurs="unbounded" minOccurs="1" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute type="folderType" name="folder" use="required" />
        </xs:complexType>
    </xs:element>
    
    <xs:complexType name="storyType">
        <xs:sequence>
            <xs:element name="slides">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="slide" type="storySlideType" maxOccurs="unbounded" minOccurs="1" />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="title" type="xs:string" use="optional" />
        <xs:attribute name="state" type="stateType" use="optional" />
        <xs:attribute name="points" type="xs:int" use="optional" />
        <xs:attribute name="mksid" type="xs:double" use="optional" />    
    </xs:complexType>
    
    <xs:simpleType name="folderType">
        <xs:restriction base="xs:string">
            <xs:minLength value="1" />
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="storySlideType">
        <xs:sequence minOccurs="0" maxOccurs="unbounded">
            <xs:any processContents="lax" minOccurs="0" maxOccurs="unbounded" namespace="##any"/>
        </xs:sequence>
        <xs:attribute name="type">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="model-context" />
                    <xs:enumeration value="story-context" />
                    <xs:enumeration value="story-narrative" />
                    <xs:enumeration value="story-demo" />
                    <xs:enumeration value="story-timeline" />
                    <xs:enumeration value="story-code-q" />
                    <xs:enumeration value="whats-next" />
                    <xs:enumeration value="sprint-intro" />
                    <xs:enumeration value="sprint-goal" />
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>

    <xs:simpleType name="stateType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="story done"></xs:enumeration>
            <xs:enumeration value="story uncommitted"></xs:enumeration>
            <xs:enumeration value="story not-done"></xs:enumeration>
            <xs:enumeration value="bug"></xs:enumeration>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== johantre/XsltSprintReviewPC/team-ba/140328/sprint-review.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="../../style/slides.xsl"?>

<sprintreview folder="140328" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../style/sprint-review.xsd">
    <team name="team-ba">
        <member type="scrummaster" capacity="0">Alexander </member>
        <member type="hands-on" capacity="4.25">Jan </member>
        <member type="hands-on" capacity="4.25">Saskia </member>
        <member type="hands-on" capacity="4.25">Michiel </member>
        <member type="hands-on" capacity="4.25">Jetro </member>
    </team>

    <stories> <!-- state can be: "story done" | "story not-done" | "story uncommitted" | "bug"  -->
        <story state="story done" points="1.25" title="ABO: Identificatie en planning increments ABO"><slides><slide type="story-narrative"></slide></slides></story>
        <story state="story done" points="0.5" title="Bijwerken SAM management (mail Gert  11/3)"><slides><slide type="story-narrative"></slide></slides></story>
        <story state="story done" points="0.25" title="Review ABO-20 en ABO-21 TO DL afsluiting"><slides><slide type="story-narrative"></slide></slides></story>
        <story state="story done" points="1" title="KB:UCM, beheer adressen, bewerk persoon UC "><slides><slide type="story-narrative"></slide></slides></story>
        <story state="story not-done" percentage-done="75" points="4" title="VVK: Verwerking review comments VVK verkoop (UCM/UCSS/LIM/SNM)"><slides><slide type="story-narrative"></slide></slides></story>
        <story state="story not-done" percentage-done="99" points="0.75" title="Matrix 5 KB: Commerciële historiek tonen (events, acties en UI definiëren: cfr. SAM, Card mgmt)"><slides><slide type="story-narrative"></slide></slides></story>
        <story state="story done" points="0.25" title="Matrix 6 KB: aanmaken klant e-ID, Mobib-kaart andere OV"><slides><slide type="story-narrative"></slide></slides></story>
        <story state="story done" points="0.5" title="Aanpassingsvoorstel ABO-08 TO Terugbetalingen (input voor Wouter)"><slides><slide type="story-narrative"></slide></slides></story>
        <story state="story done" points="3" title="PO"><slides><slide type="story-narrative"></slide></slides></story>
        <story state="story not-done" percentage-done="99" points="1" title="WBS DBS"><slides><slide type="story-narrative"></slide></slides></story>
        <story state="story not-done" percentage-done="99" points="2.5" title="DBS Matrix 1 - Lijnwinkel FO"><slides><slide type="story-narrative"></slide></slides></story>
        <story state="story done" points="0.75" title="Voorbereiding presentatie Kickoff 21/3"><slides><slide type="story-narrative"></slide></slides></story>
        <story state="story not-done" percentage-done="0" points="0.25" title="KB VVK: scan review DL op LIM/SNM/UCM/UCSS"><slides><slide type="story-narrative"></slide></slides></story>
        <story state="story done" points="1.5" title="kick-off 21/03 De Lijn Business"><slides><slide type="story-narrative"></slide></slides></story>
   </stories>        

</sprintreview>

=== johantre/XsltSprintReviewPC/canguru/140710/sprint-review.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="../../style/slides.xsl"?>

<sprintreview folder="140710" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../style/sprint-review.xsd">
  <team name="CanGuru">
    <member type="scrummaster" capacity="0.0" avatar="../avatars/Bjorn.jpg">Bjorn Geuns</member>
    <member type="hands-on" capacity="7.0" avatar="../avatars/laurens.jpg">Laurens Robben </member>
    <member type="hands-on" capacity="0" avatar="../avatars/Jelle.jpg">Jelle Bens</member>
    <member type="hands-on" capacity="3.5" avatar="../avatars/Maarten.jpg">Maarten Claes</member>
    <member type="tester" capacity="7.0" avatar="../avatars/Carmen.jpg">Carmen Filippo</member>
    <member type="tester" capacity="5.5" avatar="../avatars/Carol.jpg">Carol Guns</member>
    <member type="productowner" capacity="0.0" avatar="../avatars/Saskia.jpg">Saskia Van Oldenborgh</member>
    <member type="productowner" capacity="0.0" avatar="../avatars/Jan.jpg">Jan Van der Borght</member>
    <member type="productowner" capacity="0.0" avatar="../avatars/Jetro.jpg">Jetro Wils</member>
  </team>

    <stories> <!-- state can be: "story done" | "story not-done" | "story uncommitted" | "bug"  -->
		<story title="RTBINC-58 [V00] Scrollen door schermen regularisatie (soms) niet mogelijk" state="story done" points="1" id="RTBINC-58">
			<slides>
				<slide type="story-narrative">
					<UL><LI>Waiting customer action -> meer uitleg gevraagd over het probleem, en ondertussen de performance van een query op dit scherm onderzocht</LI></UL>
				</slide>
			</slides>
		</story>
		<story title="RTBINC-59 [V00] Fouten bij het opzoeken van kaarten" state="story not-done" points="1" id="RTBINC-59">
			<slides>
				<slide type="story-narrative">
					<UL><LI>Er moet beslist worden wat we hiermee doen. Dit scherm is NIET meer in de laatste release (die bij hun nog niet in productie staat).</LI></UL>
				</slide>
			</slides>
		</story>
		<story title="RTBINC-61 [V00] Onterechte dubbele betalingen in 65+" state="story done" points="1" id="RTBINC-61">
			<slides>
				<slide type="story-narrative">
					<UL><LI>Probleem in query gevonden en aangepast -> moet GRONDIG getest worden door testers (regressie op bepaalde stukken, is niet zozeer één scenario)</LI></UL>
				</slide>
			</slides>
		</story>
 		<story title="RTBINC-62 [V00] 65+ betalingen zijn vermist" state="story done" points="1" id="RTBINC-62">
			<slides>
				<slide type="story-narrative">
					<UL><LI>Waiting customer action -> een incident in productie waarvoor logfiles ontbreken, gevraagd of het nog voorvalt en of er logfiles voor die gevallen zijn dan</LI></UL>
				</slide>
			</slides>
		</story>
  		<story title="RTBINC-63 [V00] Fout in terugbetalingsvoorstel nr 461 Mobibguider" state="story done" points="1" id="RTBINC-63">
			<slides>
				<slide type="story-narrative">
					<UL><LI>Waiting customer action -> verdere uitleg gevraagd of dit zelfde probleem is als RTBINC-61</LI></UL>
				</slide>
			</slides>
		</story> 
		
	  	<story title="DLIM-818 [ABOR1] Fulfillment - Aanmaken personalisatiebatch: Entiteit- en exploitantfilter geven geen waardes" state="story done" points="1" id="DLIM-818">
			<slides>
				<slide type="story-narrative">
				</slide>
			</slides>
		</story> 	
	  	<story title="DLIM-791 [ABOR1] Detail personalisatiebatch: veld aantal personalisatieorders ontbreekt" state="story done" points="1" id="DLIM-791">
			<slides>
				<slide type="story-narrative">
				</slide>
			</slides>
		</story> 	
	  	<story title="DLIM-789 [ABOR1] Met meerdere personen eenzelfde personalisatieorder verwerken resulteert in een technische fout en crash" state="story done" points="1" id="DLIM-789">
			<slides>
				<slide type="story-narrative">
				</slide>
			</slides>
		</story> 	
<!-- 	  	<story title="DLIM-786 [ABOR1] Account: Contracttijden komen niet overeen met huidige tijd" state="story not-done" points="1" id="DLIM-786">
			<slides>
				<slide type="story-narrative">
					<UL><LI>Met analyse/architectuur uit te klaren wat nu juist de bedoeling is. Momenteel is het volgens spec.</LI></UL>
				</slide>
			</slides>
		</story>  -->	
<!-- 	  	<story title="DLIM-782 [ABOR1] Account - Account wordt gecreeerd bij het aanmaken van de offerte (ipv bij het goedkeuren van de offerte)" state="story not-done" points="1" id="DLIM-782">
			<slides>
				<slide type="story-narrative">
				</slide>
			</slides>
		</story>  -->	
	  	<story title="DLIM-778 [ABOR1] Fulfillment - Starten van een geannuleerde personalisatiebatch resulteert in technische error (concurrency issue)" state="story done" points="1" id="DLIM-778">
			<slides>
				<slide type="story-narrative">
				</slide>
			</slides>
		</story> 	

	  	<story title="[General] Investigate upgrade to new framework" state="story done" points="2" id="FrameworkUpgrade">
			<slides>
				<slide type="story-narrative">
					<UL><LI>Ingeschat op 5 dagen voor alles binnen ons team</LI></UL>
				</slide>
			</slides>
		</story> 	

	  	<story title="[ABOR3] Review en tech feasibility" state="story done" points="5" id="ABOR3Review">
			<slides>
				<slide type="story-narrative">
				</slide>
			</slides>
		</story> 
		
		<story title="[TAR] Module knowledge transfer" state="story not-done" points="4" id="TarModuleKnowledgeTransfer" percentage-done="25">
			<slides>
				<slide type="story-narrative">
				</slide>
			</slides>
		</story> 
	</stories>        
</sprintreview>

=== johantre/XsltSprintReviewPC/techTeam/140410/sprint-review.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="../../style/slides.xsl"?>

<sprintreview folder="140410" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../style/sprint-review.xsd">
    <team name="TechTeam">
        <member type="scrummaster" capacity="0">Michael De Maessschalck </member>
        <member type="hands-on" capacity="4">Bjorn Bailleul </member>
        <member type="hands-on" capacity="9">Philip Van Hoof</member>
        <member type="hands-on" capacity="5.5">Steven Wyns </member>
        <member type="hands-on" capacity="1.5">Steven Robijns </member>
        <member type="tester" capacity="4.5">Dorine Vos </member>
        <member type="tester" capacity="4">Rudy Windey </member>
        <member type="productowner" capacity="0">Rudy Windey </member>
    </team>

    <stories>
        <story points="1"   relid="01" state="story done" id="DL-11814" title="Aanpassen status updates MP (REF033A)                     " ><slides><slide type="story-narrative"></slide></slides></story>
        <story points="0.5" relid="01" state="story done" id="DL-11339" title="Optimalisatie upload SW package - QA                      " ><slides><slide type="story-narrative"></slide></slides></story>
        <story points="1"   relid="01" state="story done" id="DL-11816" title="State model: flow buiten gebruik => beheer gestopt        " ><slides><slide type="story-narrative"></slide></slides></story>
        <story points="1"   relid="01" state="story done" id="DL-11810" title="Update REF035 - Detail MP (tonen activatietijd, etc)      " ><slides><slide type="story-narrative"></slide></slides></story>
        <story points="1.5" relid="01" state="story done" id="DL-11794" title="Aanpassen vergrendelen lege SW package                    " ><slides><slide type="story-narrative"></slide></slides></story>
        <story points="1"   relid="01" state="story done" id="DL-11815" title="Aanpassen status overzicht detail release (REF020)        " ><slides><slide type="story-narrative"></slide></slides></story>
        <story points="0.5" relid="01" state="story done" id="DL-10780" title="Vertalen enumeratie algemene status release               " ><slides><slide type="story-narrative"></slide></slides></story>
        <story points="0.5" relid="01" state="story done" id="DL-11331" title="Optimalisaties verwijderen/SW package upload/min versie - QA                    " ><slides><slide type="story-narrative"></slide></slides></story>
                                   
        <story points="1"   relid="01" state="story done" id="        " title="Installatie MPM: uitproberen nieuwe aanpak                " ><slides><slide type="story-narrative"></slide></slides></story>
        <story points="0.5" relid="01" state="story done" id="        " title="Update installatiehandleiding                             " ><slides><slide type="story-narrative"></slide></slides></story>
        <story points="1.5" relid="01" state="story done" id="        " title="Migratie Tarievenmodule                                   " ><slides><slide type="story-narrative"></slide></slides></story>
        <story points="1"   relid="01" state="story not-done" percentage-done="0" id="        " title="Remote omgeving DL installeren met tarievenmodule     " ><slides><slide type="story-narrative"></slide></slides></story>
        <story points="2"   relid="01" state="story done" id="        " title="Installatie AVU R2                                        " ><slides><slide type="story-narrative"></slide></slides></story>
        <story points="1"   relid="01" state="story done" id="        " title="QA: voorbereiding test scenario's in TestLink             " ><slides><slide type="story-narrative"></slide></slides></story>
                                   
        <story points="2"   relid="01" state="story done" id="DL-11697" title="Rapport RM                                                " ><slides><slide type="story-narrative"></slide></slides></story>
        <story points="1.5" relid="01" state="story done" id="        " title="Update automatic tests: structural fixes (saga and uplaod)" ><slides><slide type="story-narrative"></slide></slides></story>
        <story points="2"   relid="01" state="story not-done" percentage-done="50" id="        " title="Build overdracht                                          " ><slides><slide type="story-narrative"></slide></slides></story>
        <story points="1"   relid="01" state="story not-done" percentage-done="0" id="DL-11813" title="Fix script CONFIG MGT SAMs                                " ><slides><slide type="story-narrative"></slide></slides></story>
        <story points="0.2" relid="01" state="story not-done" percentage-done="0" id="        " title="Analyse session expired (appfabric) - KT backoffice       " ><slides><slide type="story-narrative"></slide></slides></story>
        <story points="1.5" relid="01" state="story done" id="        " title="Documentation Nuget                                       " ><slides><slide type="story-narrative"></slide></slides></story>
    </stories>

</sprintreview>

=== johantre/XsltSprintReviewPC/itsbackoffice/140616/sprint-review.xml
<?xml version="1.0"?><?xml-stylesheet type="text/xsl" href="../../style/slides.xsl"?>
<sprintreview folder="140616" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../style/sprint-review.xsd">
    <team name="ITSbackoffice">
        <member type="productowner" capacity="0">Pieter Clavie </member>
        <member type="assisted" capacity="0">Julia Dubois </member>
        <member type="assisted" capacity="3">Christophe Lemoine </member>
        <member type="hands-on" capacity="0">Martijn Evens </member>
        <member type="scrummaster" capacity="4">Servaas Phlips </member>
        <member type="hands-on" capacity="8">Ignacio Errico </member>
        <member type="hands-on" capacity="6.5">Blaise Braye </member>
        <member type="hands-on" capacity="4">Serge Van Meerbeeck</member>
        <member type="hands-on" capacity="5.5">Gauthier Rossion </member>
        <member type="tester" capacity="6">Annelies Ivens </member>
        <member type="tester" capacity="6">Parisa Pejham </member>
        <member type="hands-on" capacity="6.5">Marnix De Groote </member>
    </team>

  <metrics>
    <metric project="ServiceSupportManager" linesofcode="35730" stepfiles="0" unittests="261" complexity="15" />
    <metric project="PoiTracker" linesofcode="10978" stepfiles="0" unittests="151" complexity="13.6227" />
    <metric project="Transmodel.Netex" linesofcode="29605" stepfiles="24" unittests="462" complexity="12.3833" />
    <metric project="DetourManager" linesofcode="17625" stepfiles="2" unittests="382" complexity="8.89249" />
    <metric project="JobOrchestration" linesofcode="2962" stepfiles="0" unittests="81" complexity="7.20614" />
  </metrics>
  <stories>
		<story id="MOBITS-1360" relid="13907" points="3" state="story done" title="Insert search adress functionality inside map control, (make it part of the general map control)"><slides><slide type="story-narrative"></slide></slides></story>
		<story id="MOBITS-1454" relid="13907" points="5" state="story done" title="Improve PoiTracker"><slides><slide type="story-narrative"></slide></slides></story>
		<story id="MOBITS-1552" relid="13907" points="3" state="story done" title="As a TCO I want to see the journey pattern of the selected POI"><slides><slide type="story-narrative"></slide></slides></story>
		<story id="MOBITS-1841" relid="13907" points="5" state="story done" title="As an obstruction manager I want to create a new version frame after a publish"><slides><slide type="story-narrative"></slide></slides></story>
		<story id="MOBITS-1885" relid="13907" points="1" state="story done" title="As a TCO I want a good screen setup and optimal use of screen space"><slides><slide type="story-narrative"></slide></slides></story>
		<story id="MOBITS-1890" relid="13907" points="3" state="story done" title="As a TCO I want a context menu in the treeview"><slides><slide type="story-narrative"></slide></slides></story>
		<story id="MOBITS-1891" relid="13907" points="3" state="story done" title="As a TCO I want that the state of the SSM screen is stored per User"><slides><slide type="story-narrative"></slide></slides></story>
		<story id="MOBITS-1895" relid="13907" points="2" state="story done" title="SPIKE: As a TCO I want to multiselect POI's on the map via a bounding box"><slides><slide type="story-narrative"></slide></slides></story>
		<story id="MOBITS-1914" relid="13907" points="2" state="story done" title="As a TCO I want to create/edit all fields in all pivots of a custom message at once"><slides><slide type="story-narrative"></slide></slides></story>
		<story id="MOBITS-1920" relid="" points="3" state="story done" title="Business key monitored vehicle journey"><slides><slide type="story-narrative"></slide></slides></story>
		<story id="MOBITS-1921" relid="" points="5" state="story done" title="create testplan 2.8"><slides><slide type="story-narrative"></slide></slides></story>
		<story id="MOBITS-1922" relid="" points="2" state="story done" title="test installers IW "><slides><slide type="story-narrative"></slide></slides></story>
		<story id="MOBITS-1872" relid="13907" points="3" state="story not-done" percentage-done="80" title="Finish Hastus Import Interface"><slides><slide type="story-narrative"></slide></slides></story>
		<story id="MOBITS-1919" relid="" points="2" state="story not-done" percentage-done="25" title="Merge hastus import branch"><slides><slide type="story-narrative"></slide></slides></story>
   
    </stories>

</sprintreview>

=== johantre/XsltSprintReviewPC/team-ba/140228/sprint-review.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="../../style/slides.xsl"?>

<sprintreview folder="140228" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../style/sprint-review.xsd">
    <team name="team-ba">
        <member type="scrummaster" capacity="0">Alexander </member>
        <member type="hands-on" capacity="4">Jan </member>
        <member type="hands-on" capacity="4">Saskia </member>
        <member type="hands-on" capacity="4">Michiel </member>
        <member type="hands-on" capacity="4">Jetro </member>
        <member type="hands-on" capacity="4">Frank </member>
    </team>

    <stories> <!-- state can be: "story done" | "story not-done" | "story uncommitted" | "bug"  -->
        <story title="Verwerken impact SS_SWR_AVU_31_Rechthebbenden_Vrijverkeerkaart_v06.01  op analyse klantenbeheer                           " state="story not-done" percentage-done="0" points="0.25"><slides><slide type="story-narrative"></slide></slides></story>
        <story title="Review Business_Test_Scenarios-ABO-R1-VVK-vs00.01                                                                         " state="story not-done" percentage-done="0" points="1"><slides><slide type="story-narrative"></slide></slides></story>
        <story title="Breakup Inkomstenbeheer                                                                                                   " state="story not-done" percentage-done="0" points="0.25"><slides><slide type="story-narrative"></slide></slides></story>
        <story title="Inkomstenbeheer analyse betalingen FO                                                                                     " state="story done" points="2"><slides><slide type="story-narrative"></slide></slides></story>
        <story title="Matrix 2: verkoop abonnementen FO: manueel aanmaken klant, upload foto, betaling cash, kaartcontracten, externe batch     " state="story done" points="4.5 "><slides><slide type="story-narrative"></slide></slides></story>
        <story title="Matrix 3: verkoop abonnementen FO: ophalen geg. RR (incl foto), pers.profiel met attest, betal. via voucher, dir. uitgifte" state="story not-done" percentage-done="15" points="4.75"><slides><slide type="story-narrative"></slide></slides></story>
        <story title="Overdracht vereistenbeheer                                                                                                " state="story done" points="0.75"><slides><slide type="story-narrative"></slide></slides></story>
        <story title="Detailanalyse MOBIB datamodel 4.2.1                                                                                       " state="story done" points="1.5 "><slides><slide type="story-narrative"></slide></slides></story>
        <story title="Tarievenmodule beheer productattributenset (contracts)                                                                    " state="story not-done" percentage-done="75" points="1.5 "><slides><slide type="story-narrative"></slide></slides></story>
        <story title="Scannen van reviewsheet VVK met als doel een estimate van het werk                                                        " state="story not-done" percentage-done="0" points="0.5"><slides><slide type="story-narrative"></slide></slides></story>
        <story title="Feedback team op UC + Migratie VP                                                                                         " state="story done" points="1"><slides><slide type="story-narrative"></slide></slides></story>
        <story title="Review integraties ABO-20 en ABO-21                                                                                       " state="story done" points="0.25"><slides><slide type="story-narrative"></slide></slides></story>
        <story title="Scannen van reviewsheet KB met als doel een estimatie van het werk                                                        " state="story done" points="0.5"><slides><slide type="story-narrative"></slide></slides></story>
        <story title="Overzicht verschil Controleregels-Validatieregels                                                                         " state="story done" points="0.25"><slides><slide type="story-narrative"></slide></slides></story>
   </stories>        

</sprintreview>
